import './globals.css'

//components
import Nav from '@/components/Nav'
import Provider from '@/components/Provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
        <Provider>
          <Nav />
          {children}
        </Provider>
        </body>
    </html>
  )
}
